services:
  mongodb:
    image : mongo:latest
    hostname: mongodb
    environment:
      - MONGO_INITDB_DATABASE=DigitalNotes
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=pass
    volumes:
      - ./mongodb/database:/data/db
    ports:
      - 27017:27017
  backend:
    build:
      context: backend
    command: python -u app.py 
    ports:
      - 5000:5000
    volumes:
      - ./backend:/app
    links:
      - mongodb